version: "3.9"

services:
  qrtick:
    build:
      context: .
    container_name: qrtick
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./qrtick:/usr/src/qrtick
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
             "
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=pgdb
      - DB_NAME=qrtick_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - pgdb

  celery:
    restart: always
    build:
      context: .
    command: >
      sh -c "celery -A qrtick worker --loglevel=info &&
             celery -A qrtick  beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
             " 
    volumes:
      - ./qrtick:/usr/src/qrtick
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DB_HOST=pgdb
      - DB_NAME=qrtick_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - pgdb
      - redis
      - qrtick

  pgdb:
    image: postgres:14.3-bullseye
    restart: always
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qrtick_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:7.0.0-bullseye

volumes:
  pgdata:
