# Generated by Django 3.2.13 on 2022-06-13 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import qrtick_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(max_length=10, unique=True, verbose_name='user id')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRCODE',
            fields=[
                ('id', models.CharField(default='qr_code_id', max_length=20, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('from_time', models.TimeField(null=True)),
                ('to_time', models.TimeField(null=True)),
                ('is_day_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='qrtick_app.userauthentication', to_field='user_id')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employed_date', models.DateField(null=True)),
                ('skills', models.TextField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('about_me', models.TextField(max_length=100, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to=qrtick_app.models.user_profile_image_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalDeparture',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('arrival_time', models.TimeField(null=True)),
                ('arrival_time_difference', models.IntegerField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('departure_time_difference', models.IntegerField(null=True)),
                ('total_time', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='qrtick_app.userprofile', to_field='user_id_id')),
            ],
        ),
    ]
